services:
  address:
    image:  address:1.0.0
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL:  "jdbc:mysql://mysql:3306/abcd?createDatabaseIfNotExist=true"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.MySQL5InnoDBDialect"
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://eureka:8761/eureka"
      TEST_ENV: test
    depends_on:
      - mysql
    restart: on-failure
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mysqldata:/var/lib/mysql
  eureka:
    image: eureka:1.0.0
    ports:
      - "8761:8761"
  gateaway:
    image: gateaway:1.0.0
    ports:
      - "8055:9090"
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://eureka:8761/eureka"
volumes:
  mysqldata:
